---
# - name: check tor settings
#   assert:
#     that:
#       - tor_networks | length > 0
#     quiet: true
#   no_log: true
#   tags:
#     - tor

- ansible.builtin.include_tasks: tor.yml
  when: ansible_os_family == "RedHat"
  tags:
    - tor
